[bibliography]
== Bibliography

* [[[Part15,dropid(repo:(current-metanorma-collection/IHO S-100 Part 15))]]],
span:title[S-100 -- Part 15: Data Protection Scheme],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part1,dropid(repo:(current-metanorma-collection/IHO S-100 Part 1))]]],
span:title[S-100 -- Part 1: Conceptual Schema Language],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part3,dropid(repo:(current-metanorma-collection/IHO S-100 Part 3))]]],
span:title[S-100 -- Part 3: General Feature Model and Rules for Application Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4a))]]],
span:title[S-100 -- Part 4a: Metadata],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10a))]]],
span:title[S-100 -- Part 10a: ISO/IEC 8211 Encoding],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10b))]]],
span:title[S-100 -- Part 10b: GML Data Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10c))]]],
span:title[S-100 -- Part 10c: HDF5 Data Model and File Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]
