[bibliography]
== Bibliography

* [[[Part1,dropid(repo:(current-metanorma-collection/IHO S-100 Part 1))]]],
span:title[S-100 -- Part 1: Conceptual Schema Language],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part2,dropid(repo:(current-metanorma-collection/IHO S-100 Part 2))]]],
span:title[S-100 -- Part 2: Management of Registers],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part2a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 2a))]]],
span:title[S-100 -- Part 2a: Concept and Data Dictionary Registers],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part2b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 2b))]]],
span:title[S-100 -- Part 2b: Portrayal Register],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part3,dropid(repo:(current-metanorma-collection/IHO S-100 Part 3))]]],
span:title[S-100 -- Part 3: General Feature Model and Rules for Application Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4a))]]],
span:title[S-100 -- Part 4a: Metadata],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4b))]]],
span:title[S-100 -- Part 4b: Metadata for Imagery and Gridded Data],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4c))]]],
span:title[S-100 -- Part 4c: Metadata - Data Quality],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part5,dropid(repo:(current-metanorma-collection/IHO S-100 Part 5))]]],
span:title[S-100 -- Part 5: Feature Catalogue],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part6,dropid(repo:(current-metanorma-collection/IHO S-100 Part 6))]]],
span:title[S-100 -- Part 6: Coordinate Reference Systems],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part7,dropid(repo:(current-metanorma-collection/IHO S-100 Part 7))]]],
span:title[S-100 -- Part 7: Spatial Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part8,dropid(repo:(current-metanorma-collection/IHO S-100 Part 8))]]],
span:title[S-100 -- Part 8: Imagery and Gridded Data],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part9,dropid(repo:(current-metanorma-collection/IHO S-100 Part 9))]]],
span:title[S-100 -- Part 9: Portrayal],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part9a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 9a))]]],
span:title[S-100 -- Part 9a: Portrayal (Lua)],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10a))]]],
span:title[S-100 -- Part 10a: ISO/IEC 8211 Encoding],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10b))]]],
span:title[S-100 -- Part 10b: GML Data Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10c))]]],
span:title[S-100 -- Part 10c: HDF5 Data Model and File Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part11,dropid(repo:(current-metanorma-collection/IHO S-100 Part 11))]]],
span:title[S-100 -- Part 11: Product Specifications],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part12,dropid(repo:(current-metanorma-collection/IHO S-100 Part 12))]]],
span:title[S-100 -- Part 12: S-100 Maintenance Procedures],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part13,dropid(repo:(current-metanorma-collection/IHO S-100 Part 13))]]],
span:title[S-100 -- Part 13: Scripting],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part14,dropid(repo:(current-metanorma-collection/IHO S-100 Part 14))]]],
span:title[S-100 -- Part 14: Online Data Exchange],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part15,dropid(repo:(current-metanorma-collection/IHO S-100 Part 15))]]],
span:title[S-100 -- Part 15: Data Protection Scheme],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part16,dropid(repo:(current-metanorma-collection/IHO S-100 Part 16))]]],
span:title[S-100 -- Part 16: Interoperability Catalogue Model],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part16a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 16a))]]],
span:title[S-100 -- Part 16a: Harmonised Portrayal of S-100 Products],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part17,dropid(repo:(current-metanorma-collection/IHO S-100 Part 17))]]],
span:title[S-100 -- Part 17: Discovery Metadata for Information Exchange Catalogues],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part18,dropid(repo:(current-metanorma-collection/IHO S-100 Part 18))]]],
span:title[S-100 -- Part 18: Language Packs],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[ISO19103,hidden(ISO 19103)]]]

* [[[ISO19135,hidden(ISO 19135:2005)]]]

* [[[ISO19126,hidden(ISO 19126:2009)]]]

* [[[ISO19117,hidden(ISO 19117:2012)]]]

* [[[ISO19109,hidden(ISO 19109:2005)]]]

* [[[ISO19115-1,hidden(ISO 19115-1:2014)]]]

* [[[ISO19115-2,hidden(ISO 19115-2:2009)]]]

* [[[ISO19113,hidden(ISO 19113)]]]

* [[[ISO19114,hidden(ISO 19114)]]]

* [[[ISO19138,hidden(ISO/TS 19138)]]]

* [[[ISO19110,hidden(ISO 19110:2005)]]]

* [[[ISO19111,hidden(ISO 19111:2007)]]]

* [[[ISO19107,hidden(ISO 19107:2003)]]]

* [[[ISO19123,hidden(ISO 19123)]]]

* [[[ISO19129,hidden(ISO/TS 19129)]]]

* [[[ISO8211,hidden(ISO/IEC 8211:1994)]]]

* [[[ISO19136,hidden(ISO 19136:2007)]]]

* [[[ISO19131,hidden(ISO 19131)]]]

* [[[ISO19157,hidden(ISO 19157)]]]

* [[[ISO19106,hidden(ISO 19106)]]]
