[bibliography]
== Bibliography

* [[[Part5,dropid(repo:(current-metanorma-collection/IHO S-100 Part 5))]]],
span:title[S-100 -- Part 5: Feature Catalogue],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part7,dropid(repo:(current-metanorma-collection/IHO S-100 Part 7))]]],
span:title[S-100 -- Part 7: Spatial Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10a))]]],
span:title[S-100 -- Part 10a: ISO/IEC 8211 Encoding],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10b))]]],
span:title[S-100 -- Part 10b: GML Data Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10c))]]],
span:title[S-100 -- Part 10c: HDF5 Data Model and File Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4a))]]],
span:title[S-100 -- Part 4a: Metadata],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4b))]]],
span:title[S-100 -- Part 4b: Metadata for Imagery and Gridded Data],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4c))]]],
span:title[S-100 -- Part 4c: Metadata - Data Quality],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part1,dropid(repo:(current-metanorma-collection/IHO S-100 Part 1))]]],
span:title[S-100 -- Part 1: Conceptual Schema Language],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]
