[bibliography]
== Bibliography

* [[[Part3,dropid(repo:(current-metanorma-collection/IHO S-100 Part 3))]]],
span:title[S-100 -- Part 3: General Feature Model and Rules for Application Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part8,dropid(repo:(current-metanorma-collection/IHO S-100 Part 8))]]],
span:title[S-100 -- Part 8: Imagery and Gridded Data],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part10c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 10c))]]],
span:title[S-100 -- Part 10c: HDF5 Data Model and File Format],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part1,dropid(repo:(current-metanorma-collection/IHO S-100 Part 1))]]],
span:title[S-100 -- Part 1: Conceptual Schema Language],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part7,dropid(repo:(current-metanorma-collection/IHO S-100 Part 7))]]],
span:title[S-100 -- Part 7: Spatial Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]
