== References

[bibliography]
=== Normative references

* [[[ISO19106,ISO 19106:2004]]]

* [[[ISO19107,ISO 19107:2003]]]

* [[[ISO19111,ISO 19111:2007]]]

* [[[ISO19118,ISO 19118:2005]]]

* [[[ISO19123,ISO 19123:2005]]]

* [[[ISO19136,ISO 19136:2007]]]

* [[[ISO19136-2,ISO 19136-2:2015]]]

* [[[ISO19139,ISO/TS 19139]]]

* [[[ISO19757-3,ISO/IEC 19757-3]]]

* [[[RFC2396,IETF RFC 2396]]]

* [[[RFC3986,IETF RFC 3986]]]

* [[[xlink,W3C XLink]]]

* [[[xml-ns,W3C xml-names]]]

* [[[xml,W3C xml]]]

* [[[xml-schema1,W3C xmlschema-1]]]

* [[[xml-schema2,W3C xmlschema-2]]]

* [[[leiri,W3C leiri]]]

[bibliography]
=== Non-normative references

The following references are listed only for informative purposes or to clarify parts of
this document. Drafts are subject to change and are not international standards.

* [[[ISODIS19107,nofetch(ISO/DIS 19107)]]],
_span:title[Geographic information -- Spatial schema (Draft -- June 2018)]_

* [[[OGC10-025r1,hidden(OGC 10-025r1)]]]

* [[[S127,hidden(IHO S-127)]]]

* [[[OGC10-129r1,hidden(OGC 10-129r1)]]]

* [[[OGC07-036,hidden(OGC 07-036)]]]

* [[[ISO19108,hidden(ISO 19108)]]]

* [[[ISO19156,hidden(ISO 19156)]]]

* [[[ISO19115-1,hidden(ISO 19115-1)]]]

* [[[ISO19115,hidden(ISO 19115)]]]

* [[[ISO19101,hidden(ISO 19101)]]]

* [[[Part3,dropid(repo:(current-metanorma-collection/IHO S-100 Part 3))]]],
span:title[S-100 -- Part 3: General Feature Model and Rules for Application Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part5,dropid(repo:(current-metanorma-collection/IHO S-100 Part 5))]]],
span:title[S-100 -- Part 5: Feature Catalogue],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part1,dropid(repo:(current-metanorma-collection/IHO S-100 Part 1))]]],
span:title[S-100 -- Part 1: Conceptual Schema Language],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part2a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 2a))]]],
span:title[S-100 -- Part 2a: Concept and Data Dictionary Registers],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part7,dropid(repo:(current-metanorma-collection/IHO S-100 Part 7))]]],
span:title[S-100 -- Part 7: Spatial Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part15,dropid(repo:(current-metanorma-collection/IHO S-100 Part 15))]]],
span:title[S-100 -- Part 15: Data Protection Scheme],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[AnnexA,dropid(repo:(current-metanorma-collection/IHO S-100 Annex A))]]],
span:title[S-100 -- Annex A: Terms and Definitions],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]
