== Scope

The general scope of <<Part4a>>, <<Part4b;and!Part4c>> has been described at the beginning of <<Part4a>>.
This Part is a metadata quality guidance and incorporates quality measures as described
in <<ISO19113>>, <<ISO19114>> and <<ISO19138>> and complies with <<ISO19106>>
which describes the rules for developing profiles of the 19100 series
standards. This guidance is applicable to IHO hydrographic data sets, data set series,
and individual features and feature properties. It is intended for hydrographic
requirements and describes how to document information about the quality of digital
geographic data.

The purpose of this Part is to:

. Provide data producers with appropriate information to characterize their geographic
data properly;
. Enable users to determine whether geographic data in a holding will be of use to them.

It defines:

. Mandatory and conditional metadata sections, metadata entities and metadata elements;
. Optional metadata elements to allow for more detailed description of geographic data.

Although this document is largely based on the standards mentioned above, additional
standards are referenced where relevant. (See section 4c-2References).
