[[app-4c-C]]
[appendix,obligation=informative]
== Hydrographic Quality Metadata Attribute Definitions

*DQ_AbsoluteExternalPositionalAccuracy*:: Closeness of reported coordinative values to
values accepted as or being true. [Per <<ISO19115>>]

*Public Attributes:*

*meanValuePositionalUncertainties[0..1] : Real*:: Mean value of the positional
uncertainties for a set of positions where the positional uncertainties are defined as
the distance between a measured position and what is considered as the corresponding
true position. [Adapted from <<ISO19138>>]

*meanExcludingOutliers[0..1] : Real*:: Mean value of the positional uncertainties,
excluding outliers. For a set of points where the distance does not exceed a defined
threshold, the arithmetical average of distances between their measured positions and
what is considered as the corresponding true positions. [Adapted from <<ISO19138>>]

*numberOfPositionalUncertaintiesAboveThreshold[0..1] : Integer*:: Number of positional
uncertainties above a given threshold for a set of positions. The errors are defined as
the distance between a measured position and what is considered as the corresponding
true position. [Adapted from <<ISO19138>>]

*rateOfPositionalErrorsAboveThreshold[0..1] : Real*:: Number of positional
uncertainties above a given threshold for a set of positions in relation to the total
number of measured positions. The errors are defined as the distance between the
measured position and what is considered as the corresponding true position. [Adapted
from <<ISO19138>>]

*covarianceMatrix[0..1] : Real Matrix*:: Symmetrical square matrix with variances of
point coordinates on the main diagonal and covariances between these coordinates as off
diagonal elements. [Adapted from <<ISO19138>>]

*linearErrorProbable[0..1] : Real*:: Half length of the interval defined by an upper
and lower limit in which the true value lies with probability 50%. [Adapted from
<<ISO19138>>]

*standardLinearError[0..1] : Real*:: Half length of the interval defined by an upper
and lower limit in which the true value lies with probability 68.3%. [Adapted from
<<ISO19138>>].

*linearMapAccuracy2Sigma[0..1] : Real*:: Half length of the interval defined by an
upper and lower limit in which the true value lies with probability 90%. [Adapted from
<<ISO19138>>].

*linearMapAccuracy3Sigma[0..1] : Real*:: Half length of the interval defined by an
upper and lower limit in which the true value lies with probability 95%. [Adapted from
<<ISO19138>>].

*linearMapAccuracy4Sigma[0..1] : Real*:: Half length of the interval defined by an
upper and lower limit in which the true value lies with probability 99%. [Adapted from
<<ISO19138>>].

*nearCertainityLinearError[0..1] : Real*:: Half length of the interval defined by an
upper and lower limit in which the true value lies with probability 99.8%. [Adapted
from <<ISO19138>>].

*RMSError[0..1] : Real*:: Standard deviation where the true value is not estimated
from the observations but known apriori. [Adapted from <<ISO19138>>].

*circularStandardDeviation[0..1] : Real*:: Radius describing a circle in which the
true point location lies with the probability of 39.4%. [Adapted from <<ISO19138>>].

*circularErrorProbable[0..1] : Real*:: Radius describing a circle in which the true
point location lies with the probability of 50%. [Adapted from <<ISO19138>>].

*circularMapAccuracyStandard[0..1] : Real*:: Radius describing a circle in which the
true point location lies with the probability of 90%. [Adapted from <<ISO19138>>].

*circularError95[0..1] : Real*:: Radius describing a circle in which the true point
location lies with the probability of 95%. [Adapted from <<ISO19138>>].

*circularNearCertaintyError[0..1] : Real*:: Radius describing a circle in which the
true point location lies with the probability of 99.8%. [Adapted from <<ISO19138>>].

*RMSErrorPlanimetry[0..1] : Real*:: Radius of a circle around a given point in which
the true value lies with true value P. [Adapted from <<ISO19138>>].

*CMASError[0..1] : Real*:: The absolute horizontal accuracy of the data's coordinates
expressed in terms of circular error at 90% probability given that a bias is present,
per the equation in <<ISO19138,table="D.48">>. [Adapted from <<ISO19138>>].

*ACE_CE90[0..1] : Real*:: The absolute horizontal accuracy of the data's coordinates
expressed in terms of circular error at 90% probability given that a bias is present,
per the equation in <<ISO19138,table="D.49">>. [Adapted from <<ISO19138>>].

*uncertaintyEllipse[0..1] : Record*:: A 2D ellipse with the two main axes indicating
the direction and magnitude of the highest and lowest uncertainty of a 2D point. The
data values are a record of real numbers corresponding to "phi" the bearing of the
major semi-axis, and "a" and "b" the length of the two axes, per the equations in
<<ISO19138,table="D.50">>. [Adapted from <<ISO19138>>].

*confidenceEllipse[0..1] : Record*:: A 2D ellipse with the two main axes indicating
the direction and magnitude of the highest and lowest uncertainty of a 2D point. The
data values are a record of real numbers corresponding to "phi" the bearing of the
major semi-axis, and "a" and "b" the length of the two axes, per the equations in
<<ISO19138,table="D.51">> and a significance level parameter. [Adapted from
<<ISO19138>>].

*DQ_AccuracyOfATimeMeasurement*:: Correctness of the temporal references of an item
(reporting of error in time measurement). [Per <<ISO19115>>]

*Public Attributes:*

*attributeValueUncertaintyMean[0..1] : Real*:: This data quality measure indicates the
attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 50%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty1Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 68.3%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty2Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 90%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty3Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 95%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty4Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 99%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty5Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 99.8%. [Adapted from <<ISO19138>>]

*DQ_CompletenessCommission*:: Excess data present in a data set. [Per <<ISO19115>>]

*Public Attributes:*

*excessItem[0..1] : Boolean*:: This data quality measure indicates that an item is
incorrectly present in the data. [Adapted from <<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that the item is in excess.
--

*numberOfExcessItems[0..1] : Integer*:: This data quality measure indicates the number
of items in the dataset, that should not have been in the dataset. [Adapted from
<<ISO19138>>]
+
--
This is an INTEGER count of the number of excess items.
--

*rateOfExcessItems[0..1] : Real*:: This data quality measure indicates the number of
excess items in the dataset in relation to the number of items that should have been
present. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 5 measured values and 4 valid values then the ratio is 5/4
and the reported rate = 1.25.
--

*numberOfDuplicateFeatureInstances[0..1] : Integer*:: This data quality measure
indicates the total number of exact duplications of feature instances within the data.
This is a count of all items in the data that are incorrectly extracted with duplicate
geometries. [Adapted from <<ISO19138>>]
+
--
This is an integer representing the error count.
--

*DQ_CompletenessOmission*:: This data absent from a data set. [Per <<ISO19115>>]

*Public Attributes:*

*missingItem[0..1] : Boolean*:: This data quality measure is an indicator that shows
that a specific item is missing in the data. [Adapted from <<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item is missing.
--

*numberOfMissingItems[0..1] : Integer*:: This data quality measure indicates the count
of all items that should have been in the dataset and are missing. [Adapted from
<<ISO19138>>]
+
--
This is an INTEGER count of the number of missing items.
--

*rateOfMissingItems[0..1] : Real*:: This data quality measure indicates the number of
missing items in the dataset in relation to the number of items that should have been
present. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 3 measured values and 5 values are required the ratio is 3/.5
and the reported rate = 0.6.
--

*DQ_ConceptualConsistancy*:: Adherence to the rules of a Conceptual Schema. [Per
<<ISO19115>>]

*Public Attributes:*

*conceptualSchemaNonCompliance[0..1] : Boolean*:: This data quality measure is an
indication that an item is not compliant to the rules of the relevant Conceptual
Schema. [Adapted from <<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item is not compliant with the rules of
the Conceptual Schema.
--

*conceptualSchemaCompliance[0..1] : Boolean*:: This data quality measure is an
indication that an item complies with the rules of the relevant Conceptual Schema.
[Adapted from <<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item is in compliance with the rules of
the Conceptual Schema.
--

*numberOfNonCompliantItems[0..1] : Integer*:: This data quality measure is a count of
all items in the dataset that are noncompliant to the rules of the Conceptual Schema.
If the Conceptual Schema explicitly or implicitly describes rules, these rules have to
be followed. Violations against such rules, for example; can be invalid placement of
features within a defined tolerance, duplication of features and invalid overlap of
features. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*numberOfInvalidSurfaceOverlaps[0..1] : Integer*:: This data quality measure is a
count of the total number of erroneous overlaps within the data. Which surfaces may
overlap and which must not is application dependent. Not all overlapping surfaces are
necessarily erroneous. When reporting this data quality measure the types of feature
classes corresponding to the illegal overlapping surfaces have to be reported as well.
[Adapted from <<ISO19138>>]
+
--
The allowable topological levels are described in the IHO/DGIWG joint profile of ISO
19107 Geographic Information Spatial Schema. Which particular topological structure may
be used with a specific dataset is defined in the Product Specification for that type
of data product, for example "Chain Node Topology" for IHO S-101.

This is an error count.
--

*nonComplianceRate[0..1] : Real*:: This data quality measure indicates the number of
items in the dataset that are noncompliant to the rules of the Conceptual Schema in
relation to the total number of these items that are expected to be in the dataset.
[Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 5 items that are non compliant and there are 100 of the items
in the dataset then the ratio is 5/100 and the reported rate = 0.05.
--

*complianceRate[0..1] : Real*:: This data quality measure indicates the number of
items in the dataset that are in compliance with the rules of the Conceptual Schema in
relation to the total number of these items that are expected to be in the dataset.
[Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 95 items that are compliant and there are 100 of the items in
the dataset then the ratio is 95/100 and the reported rate = 0.95.
--

*DQ_DomainConsistancy*:: Adherence of the values to the value domains. [Per
<<ISO19115>>]

*Public Attributes:*

*valueDomainNonConformance[0..1] : Boolean*:: This data quality measure is an
indication that an item is not in conformance with its value domain. [Adapted from
<<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item is not in conformance with its
value domain.
--

*valueDomainConformance [0..1] : Boolean*:: This data quality measure is an indication
that an item is conforming to its value domain. [Adapted from <<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item conforming to its value domain.
--

*numberOfNonconformantItems[0..1] : Integer*:: This data quality measure is a count of
all items in the dataset that are not in conformance with their value domain. [Adapted
from <<ISO19138>>]
+
--
This is an integer count.
--

*valueDomainConformanceRate[0..1] : Real*:: This data quality measure indicates the
number of items in the dataset that are in conformance with their value domain in
relation to the total number of items in the dataset. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 95 items that are in conformance and there are 100 of the
items in the dataset then the ratio is 95/100 and the reported rate = 0.95.
--

*valueDomainNonConformanceRate[0..1] : Real*:: This data quality measure indicates the
number of items in the dataset that are not in conformance with their value domain in
relation to the total number of items in the dataset. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 5 items that are in conformance and there are 100 of the
items in the dataset then the ratio is 5/100 and the reported rate = 0.05.
--

*DQ_FormatConsistancy*:: Degree to which data is stored in accordance with the
physical structure of the data set. [Per <<ISO19115>>]

*Public Attributes:*

*physicalStructureConflicts[0..1] : Integer*:: This data quality measure is a count of
all items in the dataset that are stored in conflict with the physical structure of the
dataset. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*physicalStructureConflictRate[0..1] : Real*:: This data quality measure indicates the
number of items in the dataset that are stored in conflict with the physical structure
of the dataset divided by the total number of items. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 3 items that are in conflict and there are 100 of the items
in the dataset then the ratio is 3/100 and the reported rate = 0.03.
--

*DQ_GriddedDataPositionalAccuracy*:: Closeness of gridded data position values to
values to values accepted as or being true. [Per <<ISO19113>>]

*Public Attributes:*

*circularStandardDeviation[0..1] : Real*:: Radius describing a circle in which the
true point location lies with the probability of 39.4%. [Adapted from <<ISO19138>>]

*circularErrorProbable[0..1] : Real*:: Radius describing a circle in which the true
point location lies with the probability of 50%. [Adapted from <<ISO19138>>]

*circularMapAccuracyStandard[0..1] : Real*:: Radius describing a circle in which the
true point location lies with the probability of 90%. [Adapted from <<ISO19138>>]

*circularError95[0..1] : Real*:: Radius describing a circle in which the true point
location lies with the probability of 95%. [Adapted from <<ISO19138>>]

*circularNearCertaintyError[0..1] : Real*:: Radius describing a circle in which the
true point location lies with the probability of 99.8%. [Adapted from <<ISO19138>>]

*RMSErrorPlanimetry[0..1] : Real*:: Radius of a circle around a given point in which
the true value lies with true value P. [Adapted from <<ISO19138>>]

*CMASError[0..1] : Real*:: The absolute horizontal accuracy of the data's coordinates
expressed in terms of circular error at 90% probability given that a bias is present,
per the equation in <<ISO19138,table="D.48">>. [Adapted from <<ISO19138>>]

*ACE_CE90[0..1] : Real*:: The absolute horizontal accuracy of the data's coordinates
expressed in terms of circular error at 90% probability given that a bias is present,
per the equation in <<ISO19138,table="D.49">>. [Adapted from <<ISO19138>>]

*uncertaintyEllipse[0..1] : Record*:: A 2D ellipse with the two main axes indicating
the direction and magnitude of the highest and lowest uncertainty of a 2D point. The
data values are a record of real numbers corresponding to "phi" the bearing of the
major semi-axis, and "a" and "b" the length of the two axes, per the equations in
<<ISO19138,table="D.50">>. [Adapted from <<ISO19138>>]

*confidenceEllipse[0..1] : Record*:: A 2D ellipse with the two main axes indicating
the direction and magnitude of the highest and lowest uncertainty of a 2D point. The
data values are a record of real numbers corresponding to "phi" the bearing of the
major semi-axis, and "a" and "b" the length of the two axes, per the equations in
<<ISO19138,table="D.51">> and a significance level parameter. [Adapted from
<<ISO19138>>]

*DQ_NonQuantitativeAttributeAccuracy*:: Correctness of non-quantitative attribute.
[Per <<ISO19115>>]

*Public Attributes:*

*numberOfIncorrectAttributeValues[0..1] : Integer*:: This data quality measure is
count of the total number of erroneous attribute values within the relevant part of the
dataset. It is a count of all attribute values where the value is incorrect. [Adapted
from <<ISO19138>>]

*rateOfCorrectAttributeValues[0..1] : Real*:: This data quality measure indicates the
number of correct attribute values in relation to the total number of attribute values.
[Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 97 correct attribute values and there are 100 attribute
values in total in the dataset then the ratio is 97/100 and the reported rate = 0.97.
--

*rateOfIncorrectAttributeValues[0..1] : Real*:: This data quality measure indicates
the number of attribute values where incorrect values are assigned in relation to the
total number of attribute values. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 3 incorrect attribute values and there are 100 attribute
values in total in the dataset then the ratio is 3/100 and the reported rate = 0.03
--

*S100_QualityMetadata*::

*DQ_QuantitativeAttributeAccuracy*:: Accuracy of a quantitative attribute. [Per
<<ISO19115>>]

*Public Attributes:*

*attributeValueUncertaintyMean[0..1] : Real*:: This data quality measure indicates the
attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 50%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty1Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 68.3%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty2Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 90%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty3Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 95%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty4Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 99%. [Adapted from <<ISO19138>>]

*attributeValueUncertainty5Sigma[0..1] : Real*:: This data quality measure indicates
the attribute value of uncertainty where half the length of the interval defined by an
upper and lower limit in which the true value for the quantitative attribute lies with
a probability of 99.8%. [Adapted from <<ISO19138>>]

*DQ_RelativeInternalPositionalAccuracy*:: Closeness of the relative positions of
features in a dataset to their respective relative positions accepted as or being true.
[Per <<ISO19115>>]

*Public Attributes:*

*relativeVerticalError[0..1] : Real*:: An evaluation of the random errors of one
relief feature to another in the same data set or on the same map/chart. It is a
function of the random errors in the two elevations with respect to a common vertical
datum. [Adapted from <<ISO19138>>]

*relativeHorizontalError[0..1] : Real*:: An evaluation of the random errors in the
horizontal position of one feature to another in the same data set or on the same
map/chart. [Adapted from <<ISO19138>>]

*DQ_TemporalConsistancy*:: Correctness of ordered events or sequences, if reported.
[Per <ISO19115>>]

*Public Attributes:*

*temporalConsistencyStatement[0..1] : CharacterString*:: This is a qualitative
statement of the consistency of the time measurement. There is no qualitative measure
provided for this data quality sub-element. [Adapted from <<ISO19138>>]

*DQ_TemporalValidity*:: Validity of data with respect to time. [Per <<ISO19115>>]

*Public Attributes:*

*valueDomainNonConformance[0..1] : Boolean*:: This data quality measure is an
indication that an item is not in conformance with its value domain. [Adapted from
<<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item is not in conformance with its
value domain.
--

*valueDomainConformance[0..1] : Boolean*:: This data quality measure is an indication
that an item is conforming to its value domain. [Adapted from <<ISO19138>>]
+
--
This is a Boolean where TRUE indicates that an item is conforming to its value domain.
--

*numberOfNonConformantItems[0..1] : Integer*:: This data quality measure is a count of
all items in the dataset that are not in conformance with their value domain. [Adapted
from <<ISO19138>>]
+
--
This is an integer count.
--

*valueDomainConformanceRate[0..1] : Real*:: This data quality measure indicates the
number of items in the dataset that are in conformance with their value domain in
relation to the total number of items in the dataset. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.
--

*valueDomainNonConformanceRate[0..1] : Real*:: This data quality measure indicates the
number of items in the dataset that are not in conformance with their value domain in
relation to the total number of items in the dataset. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 5 items that are in conformance and there are 100 of the
items in the dataset then the ratio is 5/100 and the reported rate = 0.05.
--

*DQ_ThematicClassificationCorrectness*:: Comparison of the classes assigned to
features or their attributes to a universe of discourse. [Per <<ISO19113>>]
+
--
For example, ground truth or reference dataset.
--

*Public Attributes:*

*numberOfIncorrectlyClassifiedItems[0..1] : Integer*:: This data quality measure is a
count of the number of incorrectly classified features. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*miscalculationRate[0..1] : Real*:: This data quality measure indicates the number of
incorrectly classified features in relation to the number of features that are supposed
to be there. [Adapted from <<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 1 items that are classified incorrectly and there are 100 of
the items in the dataset then the ratio is 1/100 and the reported rate = 0.01.
--

*misclassificationMatrix[0..1] : Integer Matrix*:: This data quality measure is a
matrix of integer numbers that indicates the number of items of class (i) classified as
class (j). The misclassification matrix is a quadratic matrix with n columns and n rows
where n denotes the number of classes under consideration. MCM (i,j) = (# items of
class (i) classified as class (j). The diagonal elements of the misclassified matrix
contain the correctly classified items, and the off diagonal items contain the number
of misclassified errors. [Adapted from <<ISO19138>>]

*relativeMiscalculationMatrix[0..1] : Real Matrix*:: This data quality measure is a
matrix of real numbers that indicates the number of items of class (i) classified as
class (j) divided by the number of items of class (i) \* 100 represented as a
percentage. The misclassification matrix has n columns and n rows where n denotes the
number of classes under consideration. RMCM (i,j) = (# items of class (i) classified as
class (j) / number of items of class (i) ) \*100. [Adapted from <<ISO19138>>]

*kappaCoefficient[0..1] : Real*:: This data quality measure is real number coefficient
to quantify the proportion of agreement of assignments to classes by removing
misclassifications. [Adapted from <<ISO19138>>]

*DQ_TopologicalConsistency*:: Measures of the topological consistency of geometric
representations of features. [Adapted from <<ISO19138>>]
+
--
NOTE: in ISO 19115, this is "Correctness of the explicitly encoded topological
characteristics of a dataset", but ISO 19138 states that the measures "will not serve
as measures of the consistency of explicit descriptions of topology using the
topological objects specified in ISO 19107", and S-100 does not explicitly encode
geometry.
--

*Public Attributes:*

*numberOfFaultyPointCurveConnections[0..1] : Integer*:: This data quality measure is a
count of the number of faulty point-curve connections in the dataset. A point curve
connection exists where different curves touch. These curves have an intrinsic
topological relationship that has to reflect the true constellation. For example, two
point-curve connections exist when there should only be one. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*rateOfFaultyPointCurveConnections[0..1] : Real*:: This data quality measure indicates
the number of faulty link-node connections in relation to the number of supposed
link-node connections. This data quality measure gives the erroneous point-curve
connections in relation to the total number of point-curve connections. [Adapted from
<<ISO19138>>]
+
--
This is a RATE which is a ratio, and is expressed as a REAL number representing the
rational fraction corresponding to the numerator and denominator of the ratio.

For example, if there are 2 items that are faulty link-node connections and there are
100 of the connections in the dataset then the ratio is 2/100 and the reported rate =
0.02.
--

*numberOfMissingConnectionsUndershoots[0..1] : Integer*:: This data quality measure is
a count of items in the dataset within the parameter tolerance that are mismatched due
to undershoots. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*numberOfMissingConnectionsOvershoots[0..1] : Integer*:: This data quality measure is
a count of items in the dataset within the parameter tolerance that are mismatched due
to overshoots. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*numberOfInvalidSlivers[0..1] : Integer*:: This data quality measure is a count of all
items in the dataset that are invalid sliver surfaces. A sliver is an unintended area
that occurs when adjacent surfaces are not digitized properly. The borders of the
adjacent surfaces may unintentionally gap or overlap to cause a topological error.
[Adapted from <<ISO19138>>]
+
--
This is an integer count.
--

*numberOfInvalidSelfIntersects[0..1] : Integer*:: This data quality measure is a count
of all items in the dataset that illegally intersect with themselves. [Adapted from
<<ISO19138>>]
+
--
This is an integer count.
--

*numberOfInvalidSelfOverlaps[0..1] : Integer*:: This data quality measure is a count
of all items in the dataset that illegally self-overlap. [Adapted from <<ISO19138>>]
+
--
This is an integer count.
--
