[[cls-9a-11]]
== Drawing Instructions

Drawing instructions are provided to the host using DEF as described in
<<Part13,clause="13-6.1">>. A single drawing instruction is equivalent to a single DEF element.

This section describes the model and schema for drawing instructions.

[[cls-9a-11.1]]
=== The concepts of drawing instructions

[[cls-9a-11.1.1]]
==== General concept

As in <<Part9>>, the output of the portrayal engine is a set of drawing instructions.
These typically link the feature instance to a symbol and/or alert reference. The
geometry is either taken from the feature type or can be generated by the portrayal
functions. The latter is supported by the concept of augmented geometry as described in
<<Part9,clause="9-11.1.13">>.

The conceptual model for Part 9a drawing instructions is a command-driven state
machine. This model is consistent with both SVG and <<S52>> DAI, but differs from <<Part9>>
which uses stateless drawing instructions.

To implement Part 9a drawing instructions, the host must maintain state while executing
the drawing instructions for a given feature instance. For example, if a drawing
instruction sets a pen colour, that pen colour should also be used for subsequent draw
instructions. The state must be reset prior to executing the drawing instructions for
each feature instance.

[[cls-9a-11.2]]
=== Model of the Drawing Instructions

As in <<Part9>>, this section describes the output of the portrayal functions. A single
domain-specific scripting host function, see <<cls-9a-14.2.1>> _HostPortrayalEmit_,
provides the drawing instructions for each feature instance.

Each drawing instruction is encoded in a DEF element as described in
<<Part13,clause="13-6.1".
A drawing instruction is an ordered pair comprised of a command and a parameter
list. The command is encoded in a DEF item, and the commands parameters are encoded in
a DEF parameter list.

[[tab-9a-2]]
.DEF encoding of Drawing Instructions
[cols=3,options=header]
|===
| Portrayal Item | DEF Encoding | Example

| Drawing Instruction | Element | FillColor:CHBRN,0
| Command | Item | FillColor
| Parameter List | Parameter List | CHBRN,0
| Parameter | Parameter | CHBRN
|===

Each drawing instruction contains a single case sensitive command. Each command has
zero or more parameters.

There are two types of commands: drawing commands and state commands. Drawing commands
instruct the host to render graphics. State commands instruct the host to set the state
for subsequent drawing commands.

Each command and its parameters are described in the following sub-sections, grouped by
purpose. In the tables which follow, the Type column is as described in <<Part13,table="13-7">>.
The *X-Ref* column refers to the equivalent <<Part9>> drawing instruction concept.
The <<Part9>> reference may contain relevant information such as range of expected values
or units.

[[cls-9a-11.2.1]]
==== Drawing Commands

Drawing commands are used to render graphics. They are analogous to realizations of the
<<Part9,clause="9-11.2">> _DrawingInstruction_ class. The drawing commands are listed in
<<tab-9a-3>> and each command is described on the following pages.

[[tab-9a-3]]
.Drawing Commands
[cols="a,a,a,a",options=header]
|===
| Command | Parameters | Parameter Type | <<Part9>> Reference

| PointInstruction | symbol | string | <<Part9,clause="9-11.2.7">>

<<Part9,clause="9-11.2.13">>
| LineInstruction | lineStyle | string | <<Part9,clause="9-11.2.8">>

<<Part9,clause="9-11.2.15">>

<<Part9,clause="9-11.2.16">>
| LineInstructionUnsuppressed | lineStyle | string | <<Part9,clause="9-11.2.8">>

<<Part9,clause="9-11.2.15">>

<<Part9,clause="9-11.2.16">>
.2+| ColorFill | Token | string .2+| <<Part9,clause="9-11.2.9">>

<<Part9,clause="9-12.5.1.4">>

<<Part9,clause="9-11.2.17">>
| transparency | double
| AreaFillReference | reference | string | <<Part9,clause="9-11.2.9">>

<<Part9,clause="9-12.5.1.3">>

<<Part9,clause="9-11.2.17">>
| PixmapFill | reference | string | <<Part9,clause="9-11.2.9">>

<<Part9,clause="9-12.5.1.5">>

<<Part9,clause="9-11.2.17">>
.4+| SymbolFill | symbol | string .4+| <<Part9,clause="9.11.2.9">>

<<Part9,clause="9-12.5.1.6">>

<<Part9,clause="9-11.2.17">>
| v1 | Vector
| v2 | Vector
| clipSymbols | boolean
.3+| HatchFill | direction | Vector .3+| <<Part9,clause="9.11.2.9">>

<<Part9,clause="9-12.5.1.7">>

<<Part9,clause="9-11.2.17">>
| distance | double
| lineStyle | string
| TextInstruction | text | string | <<Part9,clause="9-11.2.10">>

<<Part9,clause="9-11.2.12">>
.3+| CoverageFill | attributeCode | string .3+| <<Part9,clause="9-11.1.12">>

<<Part9,clause="9-11.2.11">>

<<Part9,clause="9-12.7.4.7">>
| uom | string
| placement | string
| NullInstruction | - | - | <<Part9,clause="9-11.2.6">>
|===

The graphic rendering of each drawing command can be modified by preceding state
commands, as described in <<cls-9a-11.2.2>>.

===== PointInstruction:__symbol__

Instructs the host to draw a Portrayal Catalogue symbol, placed as follows:

[[tab-9a-4]]
.PointInstruction Symbol Placement
[cols=2,options=header]
|===
| Geometry Type | Symbol Placement

| Point | At the point, then apply _LocalOffset_
| Line | Along the line by __LinePlacement__, then apply _LocalOffset_
| Area | At __AreaCRS__, then apply _LocalOffset_. Note that this can cause the symbol to be drawn at multiple locations
|===

===== LineInstruction:__lineStyle[,lineStyle,...]__

Instructs the host to stroke a line or area geometry using the specified linestyle(s).

The host must ensure line segments with lower drawing priority are suppressed (not
drawn) when coincident line segments with higher drawing priority are drawn.

Each linestyle parameter refers to either a linestyle defined within the Portrayal
Catalogue or to a linestyle created by a preceding _LineStyle_ command.

NOTE: <<Part10a,clause="10a-5.10.1">> defines how masked spatial elements are encoded in a
dataset. When executing this instruction the host must suppress the portrayal of masked
spatial elements.

===== LineInstructionUnsuppressed:__lineStyle[,lineStyle,...]__

Instructs the host to stroke a line or area geometry using the specified linestyle(s).

The line segments should be drawn without regard for coincident line segments.

Each linestyle parameter refers to either a linestyle defined within the Portrayal
Catalogue or to a linestyle created by a preceding _LineStyle_ command.

NOTE: <<Part10a,clause="10a-5.10.1">> defines how masked spatial elements are encoded in a
dataset. When executing this instruction the host must suppress the portrayal of masked
spatial elements.

===== ColorFill:__token[,transparency]__

Instructs the host to fill an area using the given colour token and transparency. If
transparency is not given, a value of zero is assumed.

===== AreaFillReference:__reference__

Instructs the host to fill an area using _areaFill_ (<<Part9,clause="9-13.3.10">>) defined
within the Portrayal Catalogue.

===== PixmapFill:__reference__

Instructs the host to fill an area using _pixmap_ (<<Part9,clause="9-13.3.5">>) defined
within the Portrayal Catalogue.

A preceding _AreaCRS_ command may set the origin of the pattern.

===== SymbolFill:__symbol,v1,v2[,clipSymbols]__

Instructs the host to fill an area using a symbol defined within the Portrayal
Catalogue. A preceding _AreaCRS_ command may set the origin of the pattern.

_symbol_:: The symbol used for the pattern.

_v1_:: The offset of the next symbol in the first dimension of the pattern according to
the local CRS.

_v2_:: The offset of the next symbol in the second dimension of the pattern according
to the local CRS.

_clipSymbols_:: If true (or missing), symbols are clipped at area boundaries. If false,
symbols extending over the area boundaries are not drawn at all.

===== HatchFill:__direction,distance,lineStyle[,lineStyle]__

Instructs the host to fill an area using a hatch symbol defined within the Portrayal
Catalogue. Direction and distance are as defined in <<Part9,clause="9-12.5.1.8">>.

Each linestyle parameter refers to either a linestyle defined within the Portrayal
Catalogue or to a linestyle created by a preceding _LineStyle_ command.

A preceding _AreaCRS_ command may set the origin of the pattern.

_direction_:: The vector defining the direction of the set of lines.

_distance_:: The distance between the lines measure perpendicular to the direction.

_lineStyle_:: A reference to a line style used for each hatch line.

===== TextInstruction:__text__

Instructs the host to draw the specified text placed as follows:

[[tab-9a-5]]
.TextInstruction Initial Placement
[cols=2,options=header]
|===
| Geometry Type | Initial Placement

| Point | Relative to the point
| Line | Relative to the line as determined by _LinePlacement_
| Area | Relative to _AreaCRS_. Note that this can cause the text to be drawn at multiple locations
|===

Once the initial positioning is determined, the text is offset as specified by state
commands _LocalOffset_ and _TextVerticalOffset_. The text is aligned as specified by
state commands _TextAlignHorizontal_ and _TextAlignVertical_.

If preceded by a _FontReference_ command the font is as specified in the Portrayal
Catalogue. Otherwise the host should construct a font using the values specified by
preceding _FontColor, FontSize, FontProportion, FontWeight, FontSlant, FontSerifs_ and
_FontStrikethrough_ state commands.

_text_:: The text to display.

===== CoverageFill:__attributeCode[,uom[,placement]]__

Instructs the host to fill a coverage using the lookup table entries created via the
_LookupEntry_ state command. The host must clear the coverage lookup list upon
completion.

_attributeCode_:: Specifies which of the features attributes to use for the lookup.

_uom_:: If present, specifies the unit of measure for the range values in the lookup
table. If not present, the range values and attribute value share the same unit of
measure as defined in the Feature Catalogue.

_placement_:: If present, specifies the placement of symbol/text annotations.

NOTE: When associating alerts with coverage values there may or may not be portrayal
elements present in the coverage lookup list.

===== NullInstruction

Used to indicate a feature is purposefully not portrayed. Can associate an alert with a
feature or geometry which is not portrayed, or whose alert geometry is different than
the portrayed geometry.

[[cls-9a-11.2.2]]
==== State Commands

State commands are used to set or modify the state for drawing commands which follow.
To implement the portrayal the host should associate each parameter of a state command
with a variable; each state command modifies the value of one or more of these
variables.

The host should set the initial state as indicated in the tables of the following
subsections. The state should be reset prior to executing the drawing instructions for
each feature instance.

For each state command listed in the following sub-sections the applicability is given;
this indicates which commands use the variables set by the state command.

<<tab-9a-6>> shows the different types of state commands.

[[tab-9a-6]]
.Types of State Commands
[cols=3,options=header]
|===
| Command Type | Command | Purpose

.8+| Visibility | ViewingGroup .8+| Modifies the visibility and drawing order of drawing commands
| DisplayPlane
| DrawingPriority
| ScaleMinimum
| ScaleMaximum
| Id
| Parent
| Hover
.6+| Transform | LocalOffset .6+| Applies transformations to elements drawn by drawing commands
| LinePlacement
| AreaPlacement
| AreaCRS
| Rotation
| ScaleFactor
.3+| Line Style | LineStyle .3+| Defines linestyles for use by drawing commands
| LineSymbol
| Dash
.13+| Text Style | FontColor .13+| Modifies the appearance of text drawn by drawing commands
| FontSize
| FontProportion
| FontWeight
| FontSlant
| FontSerifs
| FontUnderline
| FontStrikethrough
| FontUpperline
| FontReference
| TextAlignHorizontal
| TextAlignVertical
| TextVerticalOffset
.2+| Colour Override | OverrideColor .2+| Overrides the colours defined within a symbol or pixmap referenced by drawing commands
| OverrideAll
.9+| Geometry | SpatialReference .9+| Defines new geometries (augmented geometry) or restricts the geometry used by drawing commands
| AugmentedPoint
| AugmentedRay
| AugmentedPath
| Polyline
| Arc3Points
| ArcByRadius
| Annulus
| ClearGeometry
.4+| Coverage | LookupEntry .4+| Defines lookup entries which can be referenced by the _CoverageFill_ drawing command
| NumericAnnotation
| SymbolAnnotation
| CoverageColor
.5+| Time | Date .5+| Defines time intervals
| Time
| DateTime
| TimeValid
| ClearTime
| Alert | AlertReference | Associates geometries with alert catalogue entries
|===

[[cls-9a-11.2.2.1]]
===== Visibility Commands

Visibility commands affect the visibility and drawing order of all subsequent drawing
commands. They correspond to attributes of the <<Part9,clause="9-11.2.2">>
_DrawingInstruction_ class.

[[tab-9a-7]]
.Visibility Commands
[cols=6,options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.3+| ViewingGroup | viewingGroup .3+| string[] .3+| ""- .3+| <<Part9,clause="9-11.1.3">> .3+| For example: 21000
| ...
| viewingGroupN
| DisplayPlane
| displayPlane
| string
| ""
| <<Part9,clause="9-11.1.5">>
| For example: overRadar

| DrawingPriority
| drawingPriority
| integer
| 0
| <<Part9,clause="9-11.1.6">>
|

| ScaleMinimum
| scaleMinimum
| integer
| max integer
| <<Part9,clause="9-11.2.2">>
|

| ScaleMaximum
| scaleMaximum
| integer
| min integer
| <<Part9,clause="9-11.2.2">>
|

| Id
| id
| string
| ""
| <<Part9,clause="9-11.2.2">>
|

| Parent
| id
| string
| ""
| <<Part9,clause="9-11.2.2">>
|

| Hover
| hover
| boolean
| false
| <<Part9,clause="9-11.2.2">>
|
|===

====== ViewingGroup:__viewingGroup[,viewingGroup2[,...]]__

Sets the viewing group(s) for drawing commands which follow. The drawing command is
disabled if any viewing group is disabled.

*Applicability*: All drawing commands

====== DisplayPlane:__displayPlane__

Sets the display plane for drawing commands which follow.

*Applicability*: All drawing commands except _NullInstruction_

====== DrawingPriority:__drawingPriority__

Sets the drawing priority for drawing commands which follow.

*Applicability*: All drawing commands except _NullInstruction_

====== ScaleMinimum:__scaleMinimum__

Sets the scale denominator defining the minimum scale for drawing commands which follow.

*Applicability*: All drawing commands except _NullInstruction_

====== ScaleMaximum:__scaleMaximum__

Sets the scale denominator defining the maximum scale for drawing commands which follow.

*Applicability*: All drawing commands except _NullInstruction_

====== Id__[:id]__

Sets an identifier for drawing commands which follow. When no parameters are present,
resets to the default state of no identifier.

_id_:: An identifier for drawing commands which follow

*Applicability*: All drawing commands

====== Parent__[:id]__

Visibility of drawing commands which follow is dependent on the referenced drawing
command(s). If no referenced drawing command is executed during rendering then the
dependent drawing commands should not be executed.

In order to express cross-feature dependencies, the referenced drawing command(s) may
be associated with a feature instance other than the current feature instance; examine
all drawing commands for all feature instances when determining the parent drawing
command(s).

Execution of referenced (parent) drawing commands can be affected by many aspects of
the visualization process including viewing group settings, display plane visibility,
line suppression, scale minimum/maximum, date dependency, hover status and dependencies
of the parent drawing command.

When no parameters are present, resets to the default state of no parent dependency.

_id_:: The identifier of the parent drawing command(s)

*Applicability*: All drawing commands except _NullInstruction_

====== Hover:__hover__

Specifies whether visibility of drawing commands which follow is dependent on
hover-over. OEM implementation of support for this feature is optional.

_hover_::

_true_::: Visibility is dependent on hover-over

_false_::: Visibility is not dependent on hover-over

*Applicability*: All drawing commands except _NullInstruction_

[[cls-9a-11.2.2.2]]
===== Transform Commands

Transform commands apply transformations to elements, such as symbols, rendered by
applicable drawing commands which follow.

[[tab-9a-8]]
.Transform Commands
[cols="a,a,a,a,a",options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 Reference

.2+| LocalOffset | xOffsetMM | double | 0 .2+| <<Part9,clause="9-12.2.2.7">>
| yOffsetMM | double | 0
.4+| LinePlacement | linePlacementMode | string | Relative .4+| <<Part9,clause="9-12.3.1.5">>
| offset | double | 0.5
| endOffset | double | nil
| visibleParts | boolean | false
| AreaPlacement | areaPlacementMode | string | VisibleParts | <<Part9,clause="9-12.3.1.6">>
| AreaCRS | areaCRSType | string | GlobalGeometry | <<Part9,clause="9-12.5.1.9">>
.2+| Rotation | rotationCRS | string | PortrayalCRS .2+| <<Part9,clause="9-12.2.2.7">>

<<Part9,clause="9-12.3.1.1">>

<<Part9,clause="9-12.4.1.4">>

<<Part9,clause="9-12.6.3.5">>
| rotation | double | 0
| ScaleFactor | scaleFactor | double | 1.0 | <<Part9,clause="9-12.2.2.7">>

<<Part9,clause="9-12.3.1.1">>

<<Part9,clause="9-12.4.1.4">>
|===

====== LocalOffset:__xOffsetMM,yOffsetMM__

Specifies an offset from the geographic position using the Local CRS to be applied to
subsequent drawing commands.

*Applicability:* _PointInstruction, SymbolFill, TextInstruction_

====== LinePlacement:__linePlacementMode,offset[,endOffset][,visibleParts]__

Specifies the placement along a line for symbols or text output by subsequent drawing
commands.

_linePlacementMode_::

_Relative offset_::: is in homogenous coordinates, 0 for the start and 1 for the end of
the curve.

_Absolute offset_::: specifies the distance from the start of the curve.

_offset_:: The offset from the start of the curve. If _endOffset_ is also specified
this indicates the start point of any _TextInstruction_ command.

_endOffset_:: If present, indicates the text drawn by any _TextInstruction_ is depicted
along the linear geometry.
+
--
If present andcontains a value, further indicates the end point of any
_TextInstruction_ command. Horizontal alignment has no effect in this case.
--

_visibleParts_:: If present and true, indicates the placement applies to each visible
part of the curve.

*Applicability:* _PointInstruction, TextInstruction_

====== AreaPlacement:__areaPlacementMode__

Specifies the placement within an area for symbols or text output by subsequent drawing
commands.

_areaPlacementMode_:: -- one of:

_VisibleParts_::: The symbol or text is to be placed at a representative position in
each visible part of the surface.

_Geographic_::: The symbol or text is to be placed at a representative position of the
geographic object.

*Applicability*: _PointInstruction, TextInstruction_

====== AreaCRS:__areaCRSType__

Specifies how fill patterns output by subsequent drawing commands are anchored.

_areaCRSType_:: -- one of:

_Global_::: The anchor point is consistent with a location on the drawing device; for
example, starting with the corner of the screen. As the screen pans the pattern will
appear to shift/move through the object on screen.

_LocalGeometry_::: The anchor point is consistent with the local geometry of the object
being depicted, for example the upper left corner of the object. Patterns of adjacent
objects may not match.

_GlobalGeometry_::: The anchor point of the fill pattern is defined at a common
location such that patterns remain consistent relative to all area objects.

*Applicability*: _AreaFillReference, PixmapFill, SymbolFill, HatchFill, TextInstruction_

====== Rotation:__rotationCRS,rotation__

Specifies the rotation angle for symbols or text output by subsequent drawing commands.

_rotationCRS_:: -- one of:

_GeographicCRS_::: A geographic CRS with axis latitude and longitude measured in
degrees. _rotation_ is defined as clockwise from the true north direction.

_PortrayalCRS_::: A Cartesian coordinate system with the y-axis pointing upwards.
_rotation_ is defined in degrees clockwise from the positive y-axis.

_LocalCRS_::: A Cartesian coordinate system originated at a local geometry. _rotation_
is in degrees clockwise from the positive y-axis.

_LineCRS_::: A none-Cartesian coordinate system where the x-axis is following the
geometry of a curve and the y-axis is perpendicular to the x-axis (positive to the left
of the x-axis).
+
--
Units on the axes and for distances are millimetres. Angles are measured in degrees
clockwise from the positive y-axis.
--

See <<Part9,clause="9-12.2.2.7">> for details.

*Applicability*: _PointInstruction, SymbolFill, TextInstruction, CoverageFill_

====== ScaleFactor:__scaleFactor__

Specifies a scale factor to be applied to symbols or text output by subsequent drawing
commands.

*Applicability*: _PointInstruction, SymbolFill, TextInstruction, CoverageFill_

[[cls-9a-11.2.2.3]]
===== Line Style Commands

Line style commands create linestyles which may be referenced by subsequent drawing
commands. These commands are part of the functionality of the _LineStyles_ package
described in <<Part9,clause="9-12.4">>.

[[tab-9a-9]]
.LineStyle Commands
[cols=6,options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.2+| Dash | start | double | - .2+| <<Part9,clause="9-12.4.1.3">> .2+| Units: millimetres
| length | double | -
.5+| LineSymbol
| reference
| string
| -
.5+| <<Part9,clause="9-12.4.1.4">>
.5+|

| position | double | -
| rotation | double | 0
| crsType | CRSType | LocalCRS
| scaleFactor | double | 1.0
.8+| LineStyle
| name
| string
| -
.8+a| <<Part9,clause="9-12.4.1.1">>

<<Part9,clause="9-12.4.1.2">>
.8+|

| intervalLength | double | -
| width | double | -
| token | string | -
| transparency | double | 0
| capStyle | string | Butt
| joinStyle | string | Miter
| offset | double | 0.0
|===

====== Dash:__start,length__

Specifies a dash pattern for a single subsequent _LineStyle_ command. Can be repeated
to specify that multiple dash patterns apply to the single _LineStyle_ command.

NOTE: This command does not set the state for any drawing command; it only sets the
state for the _LineStyle_ command.

_start_:: The start of the dash measured from the start of the line along the x-axis of
the line CRS (units in millimetres).

_length_:: The length of the dash along the x-axis of the line CRS (units in
millimetres).

*Applicability*: _LineStyle_

====== LineSymbol:__reference,position[,rotation[,crsType[,scaleFactor]]]__

Specifies the use of a symbol for a single subsequent _LineStyle_ command. Can be
repeated to specify that multiple symbols apply to the _LineStyle_ command.

_reference_:: A reference to an external definition of the symbol graphic. This refers
to an identifier of a portrayal catalogue item.

_position_:: The position of the symbol measured from the start of the repeating
interval, along the x-axis of the line CRS (units in millimetres).

_rotation_:: The rotation angle of the symbol.

_crsType_:: The type of the CRS where the symbol has to be transformed. Possible values
are LocalCRS, LineCRS and PortrayalCRS.

_scaleFactor_:: The scale factor of the symbol.

*Applicability*: _LineStyle_

====== LineStyle:__name,intervalLength,width,token[,transparency[,capStyle[,joinStyle[,offset]]]]__

Creates a named linestyle for use by subsequent drawing commands. May be preceded by
zero or more _Dash_ and/or _LineSymbol_ commands which apply to the linestyle. If no
_Dash_ commands precede the _LineStyle_ command, a solid line is created.

_name_:: A name assigned to the linestyle and used to reference the linestyle from a
_LineInstruction_. In the event of a name collision between a Portrayal Catalogue
linestyle and a _LineStyle_ command, the _LineStyle_ command takes precedence.

_intervalLength_:: The length of a repeating interval of the line style along the
x-axis of the line CRS (units in mm). Can be omitted if a solid is being defined.

_width_:: Pen width in mm used to draw this line style.

_token_:: Specifies the colour used to draw this line style.

_transparency_:: Specifies the transparency used to draw this line style.

_capStyle_:: The decoration that is applied where a line segment ends. One of _Butt_,
_Square_, or _Round_. See <<Part9,clause="9-12.4.1.8">> _CapStyle_.

_joinStyle_:: The decoration that is applied where two line segments meet. One of
_Bevel_, _Miter_, or _Round_. See <<Part9,clause="9-12.4.1.7">> _JoinStyle_.

_offset_:: An offset perpendicular to the direction of the line. The value refers to
the y-axis of the line CRS (positive to the left, millimetres).

*Applicability*: _LineInstruction, LineInstructionUnsuppressed, HatchFill_

[[cls-9a-11.2.2.4]]
===== Text Style Commands

Text style commands modify the appearance of text drawn by subsequent drawing commands.

[[tab-9a-10]]
.Text Style Commands
[cols="a,a,a,a,a,a",options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.2+| FontColor | token | string | "" .2+| <<Part9,clause="9-12.6.3.8">>

9-12.2.2.3 .2+| Opaque
| transparency | double | 0
.2+| FontBackgroundColor | token | string | "" .2+| <<Part9,clause="9-12.6.3.8">>

9-12.2.2.3 .2+| Transparent
| transparency | double | 1
| FontSize
| bodySize
| double
| 10
| <<Part9,clause="9-12.6.3.8">>
|

| FontProportion
| proportion
| string
| Proportional
| <<Part9,clause="9-12.6.3.11">>
|

| FontWeight
| weight
| string
| Medium
| <<Part9,clause="9-12.6.3.10">>
|

| FontSlant
| slant
| string
| Upright
| <<Part9,clause="9-12.6.3.9">>
|

| FontSerifs
| serifs
| boolean
| false
| <<Part9,clause="9-12.6.3.2">>
|

| FontUnderline
| underline
| boolean
| false
| <<Part9,clause="9-12.6.3.12">>
|

| FontStrikethrough
| strikethrough
| boolean
| false
| <<Part9,clause="9-12.6.3.12">>
|

| FontUpperline
| upperline
| boolean
| false
| <<Part9,clause="9-12.6.3.12">>
|

| FontReference
| fontReference
| string
| ""
| <<Part9,clause="9-12.6.3.3">>
|

| TextAlignHorizontal
| horizontalAlignment
| string
| Start
| <<Part9,clause="9-12.6.3.14">>
|

| TextAlignVertical
| verticalAlignment
| string
| Bottom
| <<Part9,clause="9-12.6.3.13">>
|

| TextVerticalOffset
| verticalOffset
| double
| 0
| <<Part9,clause="9-12.6.3.8">>
|
|===

====== FontColor:__token[,transparency]__

Specifies the colour and transparency for glyphs drawn by subsequent drawing commands.

*Applicability*: _TextInstruction_

====== FontBackgroundColor:__token[,transparency]__

Specifies the colour and transparency used to fill the rectangle surrounding text
drawn by subsequent drawing commands.

*Applicability*: _TextInstruction, CoverageFill_

====== FontSize:__bodySize__

Specifies the size in points for text drawn by subsequent drawing commands.

*Applicability*: _TextInstruction, CoverageFill_

====== FontProportion:__proportion__

Specifies a font proportion to be used for text drawn by subsequent drawing commands.

_proportion_:: -- one of:

_MonoSpaced_::: A font where all typefaces have the same width should be selected.
Also known as 'typewriter' fonts.

_Proportional_::: A font where each typeface can have a different width should be
selected.

*Applicability*: _TextInstruction, CoverageFill_

====== FontWeight:__weight__

Specifies the font thickness for text drawn by subsequent drawing commands.

_weight_:: -- one of:

_Light_::: Typefaces are depicted as thin (standard).

_Medium_::: Typefaces are depicted thicker than __Light__, but not as thick as _Bold_.

_Bold_::: Typefaces are depicted more prominently (*Bold*).

*Applicability*: _TextInstruction, CoverageFill_

====== FontSlant:__slant__

Specifies the slant to be used for text drawn by subsequent drawing commands.

_slant_:: -- one of:

_Upright_::: Typefaces are upright.

_Italics_::: Typefaces are slanted to the right.

*Applicability*: _TextInstruction, CoverageFill_

====== FontSerifs:__serifs__

Specifies whether the font used for text drawn by subsequent drawing commands should
contain serifs.

*Applicability*: _TextInstruction, CoverageFill_

====== FontUnderline:__underline__

Specifies whether text drawn by subsequent drawing commands should be underlined.

*Applicability*: _TextInstruction_

====== FontStrikethrough:__strikethrough__

Specifies whether text drawn by subsequent drawing commands should be depicted with a
line through the center of the text.

*Applicability*: _TextInstruction_

====== FontUpperline:__upperline__

Specifies whether text drawn by subsequent drawing commands should be depicted with a
line above the text.

*Applicability*: _TextInstruction_

====== FontReference:__fontReference__

Specifies text drawn by subsequent drawing commands should be depicted using the
specified font from the Portrayal Catalogue. _fontReference_ is the identifier for the
external file within the Portrayal Catalogue.

*Applicability*: _TextInstruction_

====== TextAlignHorizontal:__horizontalAlignment__

Specifies the text placement relative to the anchor point in the horizontal direction
for subsequent drawing commands.

_horizontalAlignment_:: -- one of:

_Start_::: The anchor point is at the start of the text.

_Center_::: The anchor point is at the (horizontal) centre of the text.

_End_::: The anchor point is at the end of the text.

*Applicability*: _TextInstruction_

====== TextAlignVertical:__verticalAlignment__

Specifies the text placement relative to the anchor point in the vertical direction
for subsequent drawing commands.

_verticalAlignment_:: -- one of:

_Top_::: The anchor point is at the top of the text.

_Center_::: The anchor point is at the (vertical) centre of the text.

_Bottom_::: The anchor point is at the bottom of the em text.

*Applicability*: _TextInstruction_

====== TextVerticalOffset:__verticalOffset__

Specifies the vertical offset in mm above the anchor point of the text drawn by
subsequent _TextInstruction_ commands. Used to generate subscripts or superscripts.

*Applicability*: _TextInstruction_

[[cls-9a-11.2.2.5]]
===== Colour Override Commands

Colour override commands modify the colour of symbols and pixmaps drawn by subsequent
drawing commands.

[[tab-9a-11]]
.Colour Override Commands
[cols="a,a,a,a,a,a",options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.4+| OverrideColor
| colorToken
| string
| N/A
.4+| <<Part9,clause="9-12.2.2.6">>

9-12.3.1.2
.4+|

| colorTransparency | double | N/A
| overrideToken | string | N/A
| overrideTransparency | double | N/A
.2+| OverrideAll
| token
| string
| N/A
.2+| <<Part9,clause="9-12.2.2.5">>

9-12.3.1.1
.2+|
| transparency
| double
| N/A

| ClearOverride
|
|
|
|
|
|===

====== OverrideColor:__colorToken,colorTransparency,overrideToken,overrideTransparency__

Specifies an override colour which should be used to replace the original colour in a
symbol or pixmap rendered via a drawing command. This command can be issued multiple
times to specify more than one colour substitution.

*Applicability*: _PointInstruction, AreaFillReference, PixmapFill, SymbolFill_

====== OverrideAll:__token,transparency__

Substitutes all non-transparent colours with the given colour. This command supercedes
any _OverrideColor_ commands.

*Applicability*: _PointInstruction, AreaFillReference, PixmapFill, SymbolFill_

====== ClearOverride

Removes all colour substitutions.

*Applicability*: _PointInstruction, AreaFillReference, PixmapFill, SymbolFill_

[[cls-9a-11.2.2.6]]
===== Geometry Commands

All drawing commands defined in <<cls-9a-11.2.1>> reference geometries. Normally, this
is the geometry of the feature (analogous to <<Part9,clause="9-11.2.2">>
_DrawingInstruction::featureReference_). The host determines the feature's geometry
using the feature reference provided when drawing instructions are returned from the
portrayal via _HostPortrayalEmit_ as described in <<cls-9a-14.2.1>>. The geometry
commands defined in this section allow the normal behaviour to be overridden.

One method of overriding the normal behaviour is to constrain drawing commands so that
they reference either individual geometric elements of a feature; or any other
geometries defined in the dataset (analogous to <<Part9,clause="9-11.2.2">>
_DrawingInstruction::spatialReference_).

The second method of overriding the normal behaviour is to create an augmented
geometry (<<Part9,clause="9-11.1.13">>) using a geometry command.
Augmented geometry is used when the spatial to be referenced is not present in the
dataset. Augmented geometry created by a geometry command will be used by subsequent
drawing commands, overriding the features geometry.

This Part does not define separate augmented drawing instructions as in <<Part9>>.
Instead, all drawing commands are to use augmented geometry whenever augmented
geometry is available.

To deterimine the geometry to be used by a drawing command:

* If an augmented geometry command precedes the drawing command, the most recently
defined augmented geometry should be used.
* Otherwise, if the spatial references list is not empty, the drawing command is
applied to each spatial reference.
* Otherwise, the features geometry should be used.

To implement augmented paths, the host should maintain a segment list into which the
geometries created by the __Polyline__, __Arc3Points__, _ArcByRadius_ and _Annulus_
commands are placed. This list maintains the order in which the geometries are created.

Applied geometry commands are removed via the _ClearGeometry_ command, which also
clears the segment list. Using _ClearGeometry_ allows switching between referencing
the features geometry, augmented geometry, and spatial references.

The geometry commands are listed in the table below. The type _point_ indicates a pair
of doubles are passed as parameters.

[[tab-9a-12]]
.Geometry Commands
[cols=6,options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.2+| SpatialReference
| reference
| string
| -
.2+| <<Part9,clause="9-11.2.4">>
.2+|

| forward | boolean | true
.3+| AugmentedPoint
| crs
| CRSType
| -
.3+| <<Part9,clause="9-11.2.13">>
.3+|

| x .2+| Point | -
| y | -
.4+| AugmentedRay
| crsDirection
| CRSType
| -
.4+| <<Part9,clause="9-11.2.15">>
.4+|

| direction | double | -
| crsLength | CRSType | -
| length | double | -
.3+| AugmentedPath
| crsPosition
| CRSType
| -
| <<Part9,clause="9-11.2.16">>
|

| crsAngle
| CRSType
| -
| <<Part9,clause="9-11.2.16">>
|

| crsDistance
| CRSType
| -
| <<Part9,clause="9-11.2.16">>
|

.3+| Polyline
| point1
.3+| Point[]
.3+| -
.3+| <<Part9,clause="9-12.2.2.11">>
.3+|

| ...
| pointN
.6+| Arc3Points
| startPointX
.2+| Point
.2+| -
.6+| <<Part9,clause="9-12.2.2.13">>
.6+|

| startPointY
| medianPointX .2+| Point .2+| -
| medianPointY
| endPointX .2+| Point .2+| -
| endPointY
.5+| ArcByRadius
| centerX
.2+| Point
.2+| -
.5+| <<Part9,clause="9-12.2.2.14">>
.5+|

| centerY
| radius | double | -
| startAngle | double | 0
| angularDistance | double | 360
.6+| Annulus
| centerX
.2+| Point
.2+| -
.6+| <<Part9,clause="9-12.2.2.15">>
.6+|

| centerY
| outerRadius | double | -
| innerRadius | double | outerRadius
| startAngle | double | 0
| angularDistance | double | 360
| ClearGeometry
| -
| -
| -
| -
|
|===

====== SpatialReference:__reference[,forward]__

Specifies a reference to the spatial type components of the feature that defines the
geometry used for the depiction of drawing commands which follow. Not used when the
entire geometry of the feature should be depicted. Each time this command is called, a
new spatial reference is added to the spatial references list maintained by the host.
The spatial references list can be cleared by calling _ClearGeometry._

_reference_:: The identifier of the spatial type as defined in <<Part13,clause="13-8">>.

_forward_:: If true the spatial object is used in the direction in which it is stored
in the data. Only applies to curves and should be ignored for all other spatial types.

*Applicability*: All drawing commands

====== AugmentedPoint:__crs,x,y__

Specifies a position. Clears any active _AugmentedRay_ and _AugmentedPath_
instructions.

_crs_:: -- one of:

_GeographicCRS_::: A geographic CRS with axis latitude and longitude measured in
degrees.

_PortrayalCRS_::: A Cartesian coordinate system with the y-axis pointing upwards.
Units on the axes and for distances are millimetres.

_LocalCRS_::: A Cartesian coordinate system originated at a local geometry. Units on
the axes and for distances are millimetres.

_x,y_::: Coordinates of the point.

*Applicability*: __PointInstruction,___TextInstruction, NullInstruction_

====== AugmentedRay:__crsDirection,direction,crsLength,length__

Augments the geometry of a point feature. Specifies a line from the position of the
point feature to another position. The position is defined by the direction and the
length attributes. Clears any active _AugmentedPoint_ and _AugmentedPath_ instructions.

_crsDirection_ and _crsLength_:: -- each one of:

_GeographicCRS_::: Angles are defined clockwise from the true north direction.
Distances will be measured in metres.

_PortrayalCRS_::: A Cartesian coordinate system with the y-axis pointing upwards.
Units on the axes and for distances are millimetres. Angles are measured in degrees
clockwise from the positive y-axis.

_LocalCRS_::: A Cartesian coordinate system originated at a local geometry. Units on
the axes and for distances are millimetres. Angles are measured in degrees clockwise
from the positive y-axis.

_direction_:: The direction of the ray relative to the CRS specified.

_length_:: The length of the ray in units depending on the CRS specified.

*Applicability*: _LineInstruction, LineInstructionUnsuppressed, TextInstruction,
NullInstruction_

====== AugmentedPath:__crsPosition,crsAngle,crsDistance__

Instructs the host to gather all segments previously created by _Polyline_,
_Arc3Points_, _ArcByRadius_ and _Annulus_ commands and group them as a single
augmented geometry. The host must then clear the segment list. Clears any active
_AugmentedPoint_ and _AugmentedRay_ instructions.

To implement an augmented path, the host must maintain a segment list. Each call to
_Polyline_, _Arc3Points_, _ArcByRadius_ and _Annulus_ results in the host placing the
geometry on the segment list. These items taken in order they are added to the segment
list define the augmented path.

The CRS is specified separately for positions, angles and distances.

_crsPosition, crsAngle_ and _crsDistance_:: -- each one of:

_GeographicCRS_::: A geographic CRS with axis latitude and longitude measured in
degrees. Angles are defined clockwise from the true north direction. Distances will be
measured in metres.

_PortrayalCRS_::: A Cartesian coordinate system with the y-axis pointing upwards.
Units on the axes and for distances are millimetres. Angles are measured in degrees
clockwise from the positive y-axis.

_LocalCRS_::: A Cartesian coordinate system originated at a local geometry. Units on
the axes and for distances are millimetres. Angles are measured in degrees clockwise
from the positive y-axis.

*Applicability*: All drawing commands except _PointInstruction_

====== Polyline:__positionXstart,positionYstart,positionXto,positionYto[,positionXto,positionYto...]__

Instructs the host to add a polyline to the segment list.

_positionXstart,positionYstart,positionXto,positionYto_:: Coordinates of the segments
of the polyline.

*Applicability*: _AugmentedPath_

====== Arc3Points:__startPointX,startPointY,medianPointX,medianPointY,endPointX,endPointY__

Instructs the host to add an arc defined by three points to the segment list.

_startPointX,startPointY_:: The point where the arc starts.

_medianPointX,medianPointY_:: An arbitrary point on the arc.

_endPointX,endPointY_:: The point where the arc ends.

*Applicability*: _AugmentedPath_

====== ArcByRadius:__centerX,centerY,radius[,startAngle,angularDistance]__

Instructs the host to add an arc defined by a radius to the segment list.

_centerX,centerY_:: The centre of the arc.

_radius_:: The radius of the circle.

_startAngle,angularDistance_:: The sector defining where the arc starts and ends. If
not present the arc is a full circle.

*Applicability*: _AugmentedPath_

====== Annulus:__centerX,centerY,outerRadius[,innerRadius[,startAngle,angularDistance]]__

Instructs the host to add an annulus to the segment list. An annulus is a ring-shaped
region bounded by two concentric circles. It can optionally be bounded by two radii of
the circle.

Note that the presence of _startAngle_ and _angularDistance_ parameters does not imply
that _innerRadius_ must be present. The following is a valid command:
Annulus:0,1,2.34,,56,78

_centerX,centerY_:: The centre of the annulus.

_outerRadius_:: The radius of the larger circle.

_innerRadius_:: The radius of the smaller circle. If not present the segment describes
a sector of a circle.

_startAngle,angularDistance_:: The sector of an annulus segment.

*Applicability*: _AugmentedPath_

====== ClearGeometry

Clears any preceding geometry commands and empties the segment and spatial references
lists.

*Applicability*: _AugmentedPath, SpatialReference_

[[cls-9a-11.2.2.7]]
===== Coverage Commands

Coverage commands define lookup entries which are referenced by the _CoverageFill_
drawing command. These commands are part of the functionality of the _Coverage_
package described in <<Part9,clause="9-12.7">>. The coverage commands are listed in
<<tab-9a-13>> below.

[[tab-9a-13]]
.Coverage Commands
[cols=6,options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.3+| NumericAnnotation
| decimals
| integer
| -
.3+| <<Part9,clause="9-12.7.4.4">>
.3+|

| championChoice | ChampionChoice | -
| buffer | double | 0
.7+| SymbolAnnotation
| symbolRef
| string
| -
.7+| <<Part9,clause="9-12.7.4.5">>
.7+|

| rotationAttribute | string | -
| scaleAttribute | string | -
| rotationCRS | CRSType | PortrayalCRS
| rotationOffset | double | 0
| rotationFactor | double | 1
| scaleFactor | double | 1
.5+| CoverageColor
| startToken
| string
| -
.5+| <<Part9,clause="9-12.7.4.3">>
.5+|

| startTransparency | dDouble | 0
| endToken | string | -
| endTransparency | double | 0
| penWidth | double | 0
.4+| LookupEntry
| label
| string
| -
.4+a| <<Part9,clause="9-12.7.4.2">>

<<Part1,clause="1-4.5.3.4">>
.4+|

| lower | double | -
| upper | double | -
| closure | S100_IntervalType | -
|===

====== NumericAnnotation:__decimals,championChoice[,buffer]__

Specifies the numeric representation of a coverage instruction. When executing the
_CoverageFill_ drawing command, the numeric value should be drawn using the currently
defined font. However, instead of using the font colour set by _FontColor,
CoverageColor_ should be used.

_decimals_:: Number of decimal digits to show in subscript.

_championChoice_:: -- one of:

_Largest_::: Display the largest value in case of collision.

_Smallest_::: Display the smallest value in case of collision.

_buffer_:: Buffer to apply for collision detection in portrayal units.

*Applicability*: _LookupEntry_

====== SymbolAnnotation:__symbolRef,rotationAttribute,scaleAttribute
[,rotationCRS,rotationOffset[,rotationFactor[,scaleFactor]]]__

Specifies the symbol representation of a coverage instruction.

_symbolRef_:: The symbol from the Portrayal Catalogue to draw.

_rotationAttribute_:: The attribute code of the Coverage Attribute to use for the
symbol rotation value.

_scaleAttribute_:: The attribute code of the Coverage attribute to use for scaling the
symbol size.

_rotationCRS_:: Specifies the coordinate reference system for the rotation.

_rotationOffset_:: Used to adjust the 'rotationAttribute' value by addition before
applying. This offset is applied after _rotationFactor._ If no _rotationAttribute_ is
given, this value represents the rotation value to apply to the symbol. A value of 0
indicates no adjustment.

_rotationFactor_:: Used to adjust the 'rotationAttribute' value by multiplication
before applying. This factor is applied before _rotationOffset._ A value of 1
indicates no adjustment.

_scaleFactor_:: Used to adjust the 'scaleAttribute' value by multiplication before
applying. A value of 1 indicates no adjustment.

[example]
====
Assume a coverage has wind speed and direction attributes and the portrayal wishes to
draw an arrow showing wind direction and whose length is proportion to the wind speed.
In this example the wind direction indicates the compass direction of where the wind
is coming from and the portrayal wants to indicate the direction the wind is blowing
towards. Additionally, the portrayal wants a 20 knot wind speed to be indicated by
drawing the arrow at its normal scale. In this case the portrayal needs to rotate the
arrow by 180 degrees and scale the arrow by 1/20. The following commands could be used
to accomplish the portrayal of the arrow:

[source%unnumbered]
----
SymbolAnnotation:ARROW,windDirection,windSpeed,PortrayalCRS,180,1.0,0.05;
LookupEntry:Wind,0,360,closedInterval;
CoverageFill:windDirection
----
====

*Applicability*: _LookupEntry_

====== CoverageColor:__startToken,startTransparency[,endToken,endTransparency][,penWidth]__

Specifies the colour range to use for a coverage instruction. If _endToken_ and
_endTransparency_ are not specified, then a single colour is used.

_startToken,startTransparency_:: The colour to assign to the matching range or to use
as start point in a colour ramp when 'endColor' is defined.

_endToken,endTransparency_:: If given, the colour to use as the stopping point in a
coluor ramp. The range of values is spread linearly across the range of colours from
'startColor' to 'endColor' to produce a gradient effect.
+
--
The start and end colours shall be converted to the CIE xyL colour space and each
component (that is x, y, L and transparency) shall be interpolated individually before
converting back to sRGB for display.
--

_penWidth_:: Pen width to apply for dot colour used for discrete points.

*Applicability*: _LookupEntry_

====== LookupEntry:_label,lower,upper,closure_

Creates a lookup entry for use by a single subsequent _CoverageFill_ drawing command.
This instruction is used to associate preceding _NumericAnnotation, SymbolAnnotation_
and _CoverageColor_ commands with a single lookup table entry.

NOTE: To support associating alerts with coverage values which differ from portrayal,
preceding _NumericAnnotation_, _SymbolAnnotation_, or _CoverageColor_ commands are
not required.

NOTE: subsequent _LookupEntry_ commands require redefinition of _NumericAnnotation_,
_SymbolAnnotation_, and _CoverageColor_; for example the state of the other coverage
commands should be reset after processing _LookupEntry_.

_label_:: String used as a display label or legend field.

_lower_:: Lower value of lookup range.

_upper_:: Upper value of lookup range.

_Closure_:: Interval closure for range. See <<Part1,clause="1-4.5.3.4">>.

*Applicability*: _CoverageFill_

[[cls-9a-11.2.2.8]]
===== Time Commands

Time commands apply time intervals to drawing commands which follow. A time interval
is described by a start and end date and time. The time commands are listed in
<<tab-9a-14>>.

[[tab-9a-14]]
.Time Commands
[cols="a,a,a,a,a,a",options=header]
|===
| Command | Parameters | Type | Initial State | Clause | Notes

.2+| Date
| begin
| string
| stem:[-oo]
.2+| <<Part1,clause="1-4.5.3.10">>
.2+|

| end | string | stem:[oo]
.2+| Time
| begin
| string
| stem:[-oo]
.2+| <<Part1,clause="1-4.5.3.10">>
.2+|

| end | string | stem:[oo]
.2+| DateTime
| begin
| string
| stem:[-oo]
.2+| <<Part1,clause="1-4.5.3.10">>
.2+|

| end | string | stem:[oo]
| TimeValid
| closure
| S100_IntervalType
| -
a| <<Part1,clause="1-4.5.3.11">>

<<Part9,clause="9-11.2.2">>
|

| ClearTime
| -
| -
| -
| -
|
|===

====== Date:__[begin][,end]__

Specifies a start and/or end date for a time interval. One of _begin_ or _end_ must be
present.

_begin_:: Start of the interval. A __S100_TruncatedDate__, see <<Part1,table="1-2">>.

_end_:: End of the interval. A __S100_TruncatedDate__, see <<Part1,table="1-2">>.

*Applicability*: _TimeValid_

====== Time:__[begin][,end]__

Specifies a start and/or end time for a time interval. One of _begin_ or _end_ must be
present.

_begin_:: Start of the interval. A _Time,_ see <<Part1,table="1-2">>.

_end_:: End of the interval. A _Time_, see <<Part1,table="1-2">>.

*Applicability*: _TimeValid_

====== DateTime:__[begin][,end]__

Specifies a start and/or end date and time for a time interval. One of _begin_ or
_end_ must be present.

_begin_:: Start of the interval. A _DateTime_, see <<Part1,table="1-2">>.

_end_:: End of the interval. A _DateTime_, see <<Part1,table="1-2">>.

*Applicability*: _TimeValid_

====== TimeValid__[:closure]__

Creates a time interval which applies to drawing commands which follow. Intervals
accumulate until cleared via the _ClearTime_ command.

If any interval coincides with the viewing date of the portrayal (or other appropriate
selector) then the drawing command and its associated information (for example,
alerts) are valid, otherwise the command and its associated information are disabled.

The start and/or end values of the time interval are set by preceding _Date_,
_Time_, or _DateTime_ commands.

_closure_:: A string specifying an _S100_IntervalType._ See <<Part1,clause="1-4.5.3.4">>.
If not specified, defaults to _closedInterval_.

NOTE: A single-value interval is specified with _begin_ = _end_ and _closure_ =
_closedInterval_.

NOTE: The host must clear the state set by preceding __Date__, __Time__, and
_DateTime_ commands upon completion of this command.

*Applicability*: All drawing commands

====== ClearTime

Clears all accumulated time intervals and all state set by preceding time commands.

*Applicability*: All time commands, all drawing commands

[[cls-9a-11.2.2.9]]
===== Alert Commands

Alert commands associate alert information with the geometry of a drawing instruction.

[[tab-9a-15]]
.Alert Commands
[cols=6,options=header]
|===
| Command | Parameters | Type | Initial State | Part 9 | Notes

.3+| AlertReference
| alertReference
| string
| -
.3+a| <<Part9,clause="9-11.2.2">>

<<Part9,clause="9-11.2.5">>
.3+|

| plan | string | -
| monitor | string | -
|===

====== AlertReference__[:alertReference[,plan[,monitor]]]__

Specifies alert information to be associated with the geometry of drawing instructions
which follow.

_alertReference_:: A reference to an alert in the alert catalogue. If not provided,
clears any previously applied alert reference.

_plan_:: The viewing group the alert highlight is assigned to when active in route
planning. If not provided, no viewing group is assigned and the highlight cannot be
disabled.

_monitor_:: The viewing group the alert highlight is assigned to when active in route
monitoring. If not provided, no viewing group is assigned and the highlight cannot be
disabled.

*Applicability*: All drawing commands
