== References

The following referenced documents are required for the application of
this document. For dated references, only the edition cited applies. For
undated references, the latest edition of the referenced document
(including amendments) applies.

[bibliography]
=== Normative

* [[[ISO639-2,ISO 639-2:1998]]]

* [[[ISO19115-1,ISO 19115-1]]]

* [[[ISO19131,ISO 19131:2007]]]

* [[[ISO19157,ISO 19157]]]

[bibliography]
=== Informative

* [[[ISO8211,ISO/IEC 8211:1994]]]

* [[[ISO19104,ISO/TS 19104]]]

* [[[ISO19106,ISO 19106:2004]]]

* [[[ISO19109,ISO 19109:2005]]]

* [[[ISO19115,ISO 19115:2003]]]

* [[[ISO19123,ISO 19123]]]

* [[[ISO19136,ISO 19136]]]

* [[[ISO19138,ISO/TS 19138]]]

* [[[ISO19115-2,ISO 19115-2]]]

* [[[ISO19115-3,ISO 19115-3]]]

* [[[ISO19107,ISO 19107]]]

* [[[Part3,dropid(repo:(current-metanorma-collection/IHO S-100 Part 3))]]],
span:title[S-100 -- Part 3: General Feature Model and Rules for Application Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4a,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4a))]]],
span:title[S-100 -- Part 4a: Metadata],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4b,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4b))]]],
span:title[S-100 -- Part 4b: Metadata for Imagery and Gridded Data],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part4c,dropid(repo:(current-metanorma-collection/IHO S-100 Part 4c))]]],
span:title[S-100 -- Part 4c: Metadata - Data Quality],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part5,dropid(repo:(current-metanorma-collection/IHO S-100 Part 5))]]],
span:title[S-100 -- Part 5: Feature Catalogue],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part6,dropid(repo:(current-metanorma-collection/IHO S-100 Part 6))]]],
span:title[S-100 -- Part 6: Coordinate Reference Systems],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part7,dropid(repo:(current-metanorma-collection/IHO S-100 Part 7))]]],
span:title[S-100 -- Part 7: Spatial Schema],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part9,dropid(repo:(current-metanorma-collection/IHO S-100 Part 9))]]],
span:title[S-100 -- Part 9: Portrayal],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part15,dropid(repo:(current-metanorma-collection/IHO S-100 Part 15))]]],
span:title[S-100 -- Part 15: Data Protection Scheme],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[Part17,dropid(repo:(current-metanorma-collection/IHO S-100 Part 17))]]],
span:title[S-100 -- Part 17: Discovery Metadata for Information Exchange Catalogues],
span:edition[5.2.0],
span:organization[International Hydrographic Organization]

* [[[S101,hidden(IHO S-101)]]]

* [[[S122,hidden(IHO S-122)]]]

* [[[S124,hidden(IHO S-124)]]], _Navigational Warnings_, Edition 1.0.0, May 2023

* [[[S201,hidden(IHO S-201)]]], _Aids to Navigation_, Edition 1.1.0, October 2022

* [[[S125,hidden(IHO S-125)]]], _Navigational Services_
